import type { ProblemSet } from '../_types/problem';

const baseProblemSets: Omit<ProblemSet, 'id'>[] = [
  {
    title: 'CSS : 실무 신입 개발자가 알아야할 C언어',
    category: 'frontend',
    subCategory: 'html-css',
    badge: 'FE',
    thumbnailType: 'css',
    lastProgressDate: '2026.01.20',
    createdAt: '2026.01.20',
    solvedCount: 9,
    totalCount: 20,
  },
  {
    title: 'CSS : 실무 신입 개발자가 알아야할 C언어',
    category: 'backend',
    subCategory: 'java',
    badge: 'BE',
    thumbnailType: 'html',
    lastProgressDate: '2026.01.20',
    createdAt: '2026.01.20',
    solvedCount: 20,
    totalCount: 20,
  },
  {
    title: 'CSS : 실무 신입 개발자가 알아야할 C언어',
    category: 'cs',
    subCategory: 'network',
    badge: 'CS',
    thumbnailType: 'css',
    lastProgressDate: '2026.01.20',
    createdAt: '2026.01.20',
    solvedCount: 20,
    totalCount: 20,
  },
  {
    title: 'CSS : 실무 신입 개발자가 알아야할 C언어',
    category: 'frontend',
    subCategory: 'javascript',
    badge: 'FE',
    thumbnailType: 'js',
    lastProgressDate: '2026.01.20',
    createdAt: '2026.01.20',
    solvedCount: 20,
    totalCount: 20,
  },
  {
    title: 'CSS : 실무 신입 개발자가 알아야할 C언어',
    category: 'frontend',
    subCategory: 'javascript',
    badge: 'FE',
    thumbnailType: 'js',
    lastProgressDate: '2026.01.20',
    createdAt: '2026.01.20',
    solvedCount: 20,
    totalCount: 20,
  },
  {
    title: 'CSS : 실무 신입 개발자가 알아야할 C언어',
    category: 'frontend',
    subCategory: 'html-css',
    badge: 'FE',
    thumbnailType: 'css',
    lastProgressDate: '2026.01.20',
    createdAt: '2026.01.20',
    solvedCount: 20,
    totalCount: 20,
  },
  {
    title: 'CSS : 실무 신입 개발자가 알아야할 C언어',
    category: 'frontend',
    subCategory: 'html-css',
    badge: 'FE',
    thumbnailType: 'html',
    lastProgressDate: '2026.01.20',
    createdAt: '2026.01.20',
    solvedCount: 20,
    totalCount: 20,
  },
  {
    title: 'CSS : 실무 신입 개발자가 알아야할 C언어',
    category: 'frontend',
    subCategory: 'html-css',
    badge: 'FE',
    thumbnailType: 'html',
    lastProgressDate: '2026.01.20',
    createdAt: '2026.01.20',
    solvedCount: 20,
    totalCount: 20,
  },
  {
    title: 'CSS : 실무 신입 개발자가 알아야할 C언어',
    category: 'backend',
    subCategory: 'mysql',
    badge: 'BE',
    thumbnailType: 'js',
    lastProgressDate: '2026.01.20',
    createdAt: '2026.01.20',
    solvedCount: 20,
    totalCount: 20,
  },
  {
    title: 'CSS : 실무 신입 개발자가 알아야할 C언어',
    category: 'backend',
    subCategory: 'nodejs',
    badge: 'BE',
    thumbnailType: 'html',
    lastProgressDate: '2026.01.20',
    createdAt: '2026.01.20',
    solvedCount: 20,
    totalCount: 20,
  },
  {
    title: 'CSS : 실무 신입 개발자가 알아야할 C언어',
    category: 'frontend',
    subCategory: 'react',
    badge: 'FE',
    thumbnailType: 'css',
    lastProgressDate: '2026.01.20',
    createdAt: '2026.01.20',
    solvedCount: 20,
    totalCount: 20,
  },
  {
    title: 'CSS : 실무 신입 개발자가 알아야할 C언어',
    category: 'frontend',
    subCategory: 'nextjs',
    badge: 'FE',
    thumbnailType: 'css',
    lastProgressDate: '2026.01.20',
    createdAt: '2026.01.20',
    solvedCount: 20,
    totalCount: 20,
  },
];

export const mockProblemSets: ProblemSet[] = Array.from({ length: 60 }, (_, index) => {
  const baseProblemSet = baseProblemSets[index % baseProblemSets.length];

  return {
    ...baseProblemSet,
    id: `${baseProblemSet.category}-${baseProblemSet.subCategory}-${index + 1}`,
  };
});
