import type { Memo } from '../_types/memo';

export const mockMemos: Memo[] = [
  {
    id: 'memo-1',
    title: '제목',
    content: '최대 9줄',
    createdAt: '2011. 08. 17',
    color: 'pink',
    pinned: true,
    selected: true,
  },
  {
    id: 'memo-2',
    title: '제목',
    content:
      '최대 9줄최대 9줄최대 9줄최대 9줄최대 9줄최대 9줄최대 9줄최대 9줄최대 9줄최대 9줄최대 9줄최대 9줄최대 9줄최대 9줄최대 9줄최대 9줄...',
    createdAt: '2011. 08. 17',
    pinned: true,
    selected: true,
  },
  {
    id: 'memo-3',
    title: '제목',
    content: '최대 9줄',
    createdAt: '2011. 08. 17',
    imageSrc: '/mock/info-1.jpg',
    selected: true,
  },
  {
    id: 'memo-4',
    title: '제목',
    content: '최대 9줄',
    createdAt: '2011. 08. 17',
  },
  {
    id: 'memo-5',
    title: '제목',
    content: '최대 9줄',
    createdAt: '2011. 08. 17',
    imageSrc: '/mock/info-2.jpg',
    color: 'orange',
  },
  {
    id: 'memo-6',
    title: '제목',
    content: '최대 9줄',
    createdAt: '2011. 08. 17',
    imageSrc: '/mock/info-3.jpg',
  },
  {
    id: 'memo-7',
    title: '제목',
    content: '최대 9줄',
    createdAt: '2011. 08. 17',
  },
  {
    id: 'memo-8',
    title: '제목',
    content: '최대 9줄',
    createdAt: '2011. 08. 17',
  },
  {
    id: 'memo-9',
    title: '제목',
    content: '최대 9줄',
    createdAt: '2011. 08. 17',
  },
  {
    id: 'memo-10',
    title: '제목',
    content: '최대 9줄',
    createdAt: '2011. 08. 17',
    imageSrc: '/mock/info-4.jpg',
  },
  {
    id: 'memo-11',
    title: '제목',
    content: '최대 9줄',
    createdAt: '2011. 08. 17',
  },
  {
    id: 'memo-12',
    title: '제목',
    content: '최대 9줄',
    createdAt: '2011. 08. 17',
  },
  {
    id: 'deleted-1',
    title: '제목',
    content: '최대 9줄',
    createdAt: '2011. 08. 17',
    deleted: true,
  },
  {
    id: 'deleted-2',
    title: '제목',
    content: '최대 9줄',
    createdAt: '2011. 08. 17',
    deleted: true,
  },
  {
    id: 'deleted-3',
    title: '제목',
    content: '최대 9줄',
    createdAt: '2011. 08. 17',
    imageSrc: '/images/problem/js.png',
    deleted: true,
  },
  {
    id: 'deleted-4',
    title: '제목',
    content: '최대 9줄',
    createdAt: '2011. 08. 17',
    imageSrc: '/images/problem/js.png',
    deleted: true,
  },
];
